# Copyright Contributors to the Kazen Rigging Language project.
# SPDX-License-Identifier: BSD-3-Clause
# https://github.com/ZhongLingXiao/karl

# GitHub Actions workflow file for CI
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Linux (gcc)
on:
  push:
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
    - name: "Checkout karl"
      uses: actions/checkout@v3
      with:
        submodules: recursive    
    
    - name: "Setup CMake"
      uses: lukka/get-cmake@latest

    - name: "Setup Flex & Bison"
      run: |
           sudo apt-get install flex
           sudo apt-get install bison

    - name: "Configure"
      run: cmake -B build

    - name: "Build"
      run: cmake --build build --parallel --config Release

    - name: "Test"
      run: ${{github.workspace}}/build/bin/karl_test

  required:
    if: always()
    name: Required
    runs-on: ubuntu-22.04
    needs:
      - build-and-test
    steps:
      - name: Merge requirement checking
        run: |
          build_and_test=${{ needs.build-and-test.result }}
          if [[ $build_and_test != 'success' ]]; then
            exit 1
          fi