# Copyright Contributors to the Kazen Rigging Language project.
# SPDX-License-Identifier: BSD-3-Clause
# https://github.com/ZhongLingXiao/karl

# GitHub Actions workflow file for CI
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on:
  push:
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
jobs:
  Ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout karl
      uses: actions/checkout@v3
      with:
        submodules: recursive    
    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Install Flex & Bison
      run: |
           sudo apt-get install flex
           sudo apt-get install bison

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --parallel --config Release

    - name: Test
      run: ${{github.workspace}}/build/bin/karl_test

  MacOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout karl
      uses: actions/checkout@v3
      with:
        submodules: recursive    
    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Install Flex & Bison
      run: |
           brew install flex
           brew install bison
           echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
           source ~/.bash_profile
           bison -V
           
    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --parallel --config Release

    - name: Test
      run: ${{github.workspace}}/build/bin/karl_test