# GitHub Actions workflow file for CI
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: ci
on: [push]
jobs:
  Ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout karl.
      uses: actions/checkout@v3
    
    - name: Configure enviroment (flex & bison)
      run: |
           sudo apt-get install flex
           sudo apt-get install bison

    - name: Build Release
      run: make