# GitHub Actions workflow file for CI
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: karl-github-actions
run-name: ${{ github.actor }} is karl GitHub Actions
on: [push]
jobs:
  Ubuntu_20_04:
    run-on: ubuntu-20.04
    steps:
    - name: Checkout karl.
      use: actions/checkout@v3
    
    - name: Configure enviroment (flex & bison)
      run: |
           sudo apt-get install flex
           sudo apt-get install bison

    - name: Build Release
      run: make