# GitHub Actions workflow file for CI
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: ci
on:
  push:
    # Skip jobs when only documentation files are changed
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
jobs:
  Ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout karl
      uses: actions/checkout@v3
    
    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Install Flex & Bison
      run: |
           sudo apt-get install flex
           sudo apt-get install bison

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --parallel --config Release

    - name: Test
      run: ${{github.workspace}}/build/bin/karl < testsuite/simple/code.karl